# Dataset and dependicies.

In [3]:
import polars as pl

We use [Amazon Review Data](https://cseweb.ucsd.edu/~jmcauley/datasets/amazon_v2/), Video Games category. We download 5-core data (each item that have 5+ rates) and metadata.

In [4]:
dataset = pl.read_ndjson(r'data\Video_Games_5.json')
print(f'Num of interactions: {len(dataset)}')
dataset.sample(5)

Num of interactions: 497577

shape: (5, 11)
┌─────────┬──────┬──────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ overall ┆ vote ┆ verified ┆ reviewTime  ┆ … ┆ reviewText  ┆ summary    ┆ unixReview ┆ style      │
│ ---     ┆ ---  ┆ ---      ┆ ---         ┆   ┆ ---         ┆ ---        ┆ Time       ┆ ---        │
│ f64     ┆ str  ┆ bool     ┆ str         ┆   ┆ str         ┆ str        ┆ ---        ┆ struct[1]  │
│         ┆      ┆          ┆             ┆   ┆             ┆            ┆ i64        ┆            │
╞═════════╪══════╪══════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 5.0     ┆ null ┆ true     ┆ 12 2, 2012  ┆ … ┆ So happy I  ┆ Awesome    ┆ 1354406400 ┆ null       │
│         ┆      ┆          ┆             ┆   ┆ bought this ┆ game!!     ┆            ┆            │
│         ┆      ┆          ┆             ┆   ┆ game. I…    ┆            ┆            ┆            │
│ 4.0     ┆ null ┆ true     ┆ 12 31, 2011 ┆ … ┆ This        ┆ Get it.    ┆ 1325289600 ┆ null       │
│         ┆      ┆          ┆             ┆   ┆ product is  ┆            ┆            ┆            │
│         ┆      ┆          ┆             ┆   ┆ great so    ┆            ┆            ┆            │
│         ┆      ┆          ┆             ┆   ┆ far. …      ┆            ┆            ┆            │
│ 5.0     ┆ null ┆ false    ┆ 11 14, 2006 ┆ … ┆ I have now  ┆ THE reason ┆ 1163462400 ┆ {" Video   │
│         ┆      ┆          ┆             ┆   ┆ played      ┆ to have an ┆            ┆ Game"}     │
│         ┆      ┆          ┆             ┆   ┆ through     ┆ Xbox 360…  ┆            ┆            │
│         ┆      ┆          ┆             ┆   ┆ this…       ┆            ┆            ┆            │
│ 3.0     ┆ null ┆ false    ┆ 08 20, 2016 ┆ … ┆ Great mouse ┆ Great      ┆ 1471651200 ┆ {null}     │
│         ┆      ┆          ┆             ┆   ┆ that's      ┆ mouse      ┆            ┆            │
│         ┆      ┆          ┆             ┆   ┆ simple but  ┆ that's     ┆            ┆            │
│         ┆      ┆          ┆             ┆   ┆ …           ┆ simple but ┆            ┆            │
│         ┆      ┆          ┆             ┆   ┆             ┆ …          ┆            ┆            │
│ 5.0     ┆ null ┆ true     ┆ 02 28, 2018 ┆ … ┆ Best games  ┆ Best games ┆ 1519776000 ┆ {null}     │
│         ┆      ┆          ┆             ┆   ┆ ever on ps2 ┆ ever on    ┆            ┆            │
│         ┆      ┆          ┆             ┆   ┆             ┆ ps2        ┆            ┆            │
└─────────┴──────┴──────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

Description of dataset:

- **overall** - our target (rating)
- **vote**

In [6]:
metadata = pl.read_ndjson(r'data\meta_Video_Games.json')
metadata.sample()

shape: (1, 18)
┌─────────────┬───────┬─────────────┬─────┬───┬─────────────┬────────────┬───────────┬─────────────┐
│ category    ┆ tech1 ┆ description ┆ fit ┆ … ┆ price       ┆ asin       ┆ imageURL  ┆ imageURLHig │
│ ---         ┆ ---   ┆ ---         ┆ --- ┆   ┆ ---         ┆ ---        ┆ ---       ┆ hRes        │
│ list[str]   ┆ str   ┆ list[str]   ┆ str ┆   ┆ str         ┆ str        ┆ list[str] ┆ ---         │
│             ┆       ┆             ┆     ┆   ┆             ┆            ┆           ┆ list[str]   │
╞═════════════╪═══════╪═════════════╪═════╪═══╪═════════════╪════════════╪═══════════╪═════════════╡
│ ["Video     ┆       ┆ ["Deck      ┆     ┆ … ┆             ┆ B0026YHS3U ┆ []        ┆ []          │
│ Games",     ┆       ┆ their homes ┆     ┆   ┆ 		          ┆            ┆           ┆             │
│ "PC", …     ┆       ┆ with 40     ┆     ┆   ┆ …           ┆            ┆           ┆             │
│ "Insta…     ┆       ┆ new…        ┆     ┆   ┆             ┆            ┆           ┆             │
└─────────────┴───────┴─────────────┴─────┴───┴─────────────┴────────────┴───────────┴─────────────┘

Now we count num of users and items, we need at least 1000 of both

In [7]:
print(f'Num of users: {dataset['reviewerID'].n_unique()}')
print(f'Num of items: {dataset['asin'].n_unique()}')
assert dataset['reviewerID'].n_unique() >= 10000
assert dataset['asin'].n_unique() >= 10000

Num of users: 55223
Num of items: 17408

# Collaborative kNN filtration

We will use user-based approach. Model defined in `models/collaborative_filtration.py`.