# Dataset and dependicies.

In [3]:
%pip install polars

Requirement already satisfied: polars in c:\Users\MSI\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.0.0)
Requirement already satisfied: polars-runtime-32==2.0.0 in c:\Users\MSI\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from polars) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import polars as pl

We use [Amazon Review Data](https://cseweb.ucsd.edu/~jmcauley/datasets/amazon_v2/), Video Games category. We download 5-core data (each item that have 5+ rates) and metadata.

In [29]:
dataset = pl.read_ndjson(r'data\Video_Games_5.json')
print(f'Num of interactions: {len(dataset)}')
dataset.sample(5)

Num of interactions: 497577

shape: (5, 11)
┌─────────┬──────┬──────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ overall ┆ vote ┆ verified ┆ reviewTime  ┆ … ┆ reviewText  ┆ summary    ┆ unixReview ┆ style      │
│ ---     ┆ ---  ┆ ---      ┆ ---         ┆   ┆ ---         ┆ ---        ┆ Time       ┆ ---        │
│ f64     ┆ str  ┆ bool     ┆ str         ┆   ┆ str         ┆ str        ┆ ---        ┆ struct[1]  │
│         ┆      ┆          ┆             ┆   ┆             ┆            ┆ i64        ┆            │
╞═════════╪══════╪══════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 3.0     ┆ 7    ┆ false    ┆ 11 9, 2011  ┆ … ┆ This        ┆ Same Ole   ┆ 1320796800 ┆ {" Video   │
│         ┆      ┆          ┆             ┆   ┆ reminds me  ┆ Same Ole   ┆            ┆ Game"}     │
│         ┆      ┆          ┆             ┆   ┆ of Unreal   ┆            ┆            ┆            │
│         ┆      ┆          ┆             ┆   ┆ Tour…       ┆            ┆            ┆            │
│ 4.0     ┆ null ┆ true     ┆ 05 27, 2010 ┆ … ┆ We have had ┆ Ice age 2  ┆ 1274918400 ┆ {null}     │
│         ┆      ┆          ┆             ┆   ┆ great fun   ┆            ┆            ┆            │
│         ┆      ┆          ┆             ┆   ┆ with our…   ┆            ┆            ┆            │
│ 5.0     ┆ null ┆ true     ┆ 02 1, 2015  ┆ … ┆ exelente    ┆ Five Stars ┆ 1422748800 ┆ {" Video   │
│         ┆      ┆          ┆             ┆   ┆             ┆            ┆            ┆ Game"}     │
│ 3.0     ┆ 14   ┆ true     ┆ 03 22, 2009 ┆ … ┆ I have not  ┆ Awesome    ┆ 1237680000 ┆ null       │
│         ┆      ┆          ┆             ┆   ┆ owned a     ┆ mouse -    ┆            ┆            │
│         ┆      ┆          ┆             ┆   ┆ wired       ┆ Lousy      ┆            ┆            │
│         ┆      ┆          ┆             ┆   ┆ mouse…      ┆ Software   ┆            ┆            │
│ 5.0     ┆ null ┆ false    ┆ 11 24, 2014 ┆ … ┆ Best        ┆ wow !      ┆ 1416787200 ┆ {" Video   │
│         ┆      ┆          ┆             ┆   ┆ graphics on ┆            ┆            ┆ Game"}     │
│         ┆      ┆          ┆             ┆   ┆ ps4 . This  ┆            ┆            ┆            │
│         ┆      ┆          ┆             ┆   ┆ ga…         ┆            ┆            ┆            │
└─────────┴──────┴──────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [40]:
metadata = pl.read_ndjson(r'data\meta_Video_Games.json')
metadata.sample()

shape: (1, 18)
┌─────────────┬───────┬─────────────┬─────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ category    ┆ tech1 ┆ description ┆ fit ┆ … ┆ price       ┆ asin       ┆ imageURL   ┆ imageURLHi │
│ ---         ┆ ---   ┆ ---         ┆ --- ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ghRes      │
│ list[str]   ┆ str   ┆ list[str]   ┆ str ┆   ┆ str         ┆ str        ┆ list[str]  ┆ ---        │
│             ┆       ┆             ┆     ┆   ┆             ┆            ┆            ┆ list[str]  │
╞═════════════╪═══════╪═════════════╪═════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ ["Video     ┆       ┆ ["Envy of   ┆     ┆ … ┆             ┆ B00B17J7XW ┆ ["https:// ┆ ["https:// │
│ Games", "Ac ┆       ┆ your        ┆     ┆   ┆ 		          ┆            ┆ images-na. ┆ images-na. │
│ cessories", ┆       ┆ friends new ┆     ┆   ┆ …           ┆            ┆ ssl-images ┆ ssl-images │
│ …           ┆       ┆ DSi…        ┆     ┆   ┆             ┆            ┆ …          ┆ …          │
└─────────────┴───────┴─────────────┴─────┴───┴─────────────┴────────────┴────────────┴────────────┘

Now we count num of users and items, we need at least 1000 of both

In [39]:
print(f'Num of users: {dataset['reviewerID'].n_unique()}')
print(f'Num of items: {dataset['asin'].n_unique()}')

Num of users: 55223
Num of items: 17408

# Collaborative kNN filtration

We will use user-based approach. Model defined in `models/collaborative_filtration.py`.