# Dataset and dependicies.

In [3]:
import polars as pl

We use [Amazon Review Data](https://cseweb.ucsd.edu/~jmcauley/datasets/amazon_v2/), Video Games category. We download 5-core data (each item that have 5+ rates) and metadata.

In [10]:
dataset = pl.read_ndjson(r'data\Video_Games_5.json')
print(f'Num of reviews: {len(dataset)}')
print(dataset.columns)
dataset.sample(5)

Num of reviews: 497577
['overall', 'vote', 'verified', 'reviewTime', 'reviewerID', 'asin', 'reviewerName', 'reviewText', 'summary', 'unixReviewTime', 'style']

shape: (5, 11)
┌─────────┬──────┬──────────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ overall ┆ vote ┆ verified ┆ reviewTime  ┆ … ┆ reviewText  ┆ summary    ┆ unixReview ┆ style      │
│ ---     ┆ ---  ┆ ---      ┆ ---         ┆   ┆ ---         ┆ ---        ┆ Time       ┆ ---        │
│ f64     ┆ str  ┆ bool     ┆ str         ┆   ┆ str         ┆ str        ┆ ---        ┆ struct[1]  │
│         ┆      ┆          ┆             ┆   ┆             ┆            ┆ i64        ┆            │
╞═════════╪══════╪══════════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 3.0     ┆ null ┆ true     ┆ 12 18, 2012 ┆ … ┆ Resistance  ┆ Not what I ┆ 1355788800 ┆ {" Video   │
│         ┆      ┆          ┆             ┆   ┆ 3 is        ┆ expected   ┆            ┆ Game"}     │
│         ┆      ┆          ┆             ┆   ┆ another     ┆            ┆            ┆            │
│         ┆      ┆          ┆             ┆   ┆ fantas…     ┆            ┆            ┆            │
│ 2.0     ┆ null ┆ false    ┆ 09 2, 2016  ┆ … ┆ Very cheap, ┆ Fragile    ┆ 1472774400 ┆ {null}     │
│         ┆      ┆          ┆             ┆   ┆ lightweight ┆            ┆            ┆            │
│         ┆      ┆          ┆             ┆   ┆ and th…     ┆            ┆            ┆            │
│ 5.0     ┆ null ┆ true     ┆ 09 1, 2015  ┆ … ┆ love it     ┆ Five Stars ┆ 1441065600 ┆ {null}     │
│ 5.0     ┆ null ┆ false    ┆ 01 15, 2014 ┆ … ┆ Perfect     ┆ control    ┆ 1389744000 ┆ {null}     │
│         ┆      ┆          ┆             ┆   ┆ match for   ┆ freak      ┆            ┆            │
│         ┆      ┆          ┆             ┆   ┆ the         ┆            ┆            ┆            │
│         ┆      ┆          ┆             ┆   ┆ controll…   ┆            ┆            ┆            │
│ 4.0     ┆ null ┆ false    ┆ 05 29, 2005 ┆ … ┆ Just when   ┆ NnyCW for  ┆ 1117324800 ┆ null       │
│         ┆      ┆          ┆             ┆   ┆ you worry   ┆ Capcom     ┆            ┆            │
│         ┆      ┆          ┆             ┆   ┆ that game … ┆ City       ┆            ┆            │
└─────────┴──────┴──────────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

We have 497577 reviews in our dataset.

Description of dataset columns:

- **reviewerID** - ID of the reviewer, e.g. A2SUAM1J3GNN3B
- **asin** - ID of the product, e.g. 0000013714
- **reviewerName** - name of the reviewer
- **vote** - helpful votes of the review
- **style** - a disctionary of the product metadata, e.g., "Format" is "Video Game"
- **reviewText** - text of the review
- **summary** - summary of the review
- **unixReviewTime** - time of the review (unix time)
- **reviewTime** - time of the review (raw)
- **verified** - review left after a verified purchase
- **overall** - rating of the product (target)


We assume that product is relative if **overall**$\geq 4.0$. Recommendation is good if true overall at least 4.0

In [9]:
metadata = pl.read_ndjson(r'data\meta_Video_Games.json')
print(metadata.columns)
metadata.sample()

['category', 'tech1', 'description', 'fit', 'title', 'also_buy', 'tech2', 'brand', 'feature', 'rank', 'also_view', 'main_cat', 'similar_item', 'date', 'price', 'asin', 'imageURL', 'imageURLHighRes']

shape: (1, 18)
┌───────────┬───────┬─────────────────┬─────┬───┬────────┬────────────┬───────────┬────────────────┐
│ category  ┆ tech1 ┆ description     ┆ fit ┆ … ┆ price  ┆ asin       ┆ imageURL  ┆ imageURLHighRe │
│ ---       ┆ ---   ┆ ---             ┆ --- ┆   ┆ ---    ┆ ---        ┆ ---       ┆ s              │
│ list[str] ┆ str   ┆ list[str]       ┆ str ┆   ┆ str    ┆ str        ┆ list[str] ┆ ---            │
│           ┆       ┆                 ┆     ┆   ┆        ┆            ┆           ┆ list[str]      │
╞═══════════╪═══════╪═════════════════╪═════╪═══╪════════╪════════════╪═══════════╪════════════════╡
│ ["Video   ┆       ┆ ["Get a grip on ┆     ┆ … ┆ $99.11 ┆ B00005MCWW ┆ []        ┆ []             │
│ Games",   ┆       ┆ your racing ac… ┆     ┆   ┆        ┆            ┆           ┆                │
│ "PC", …   ┆       ┆                 ┆     ┆   ┆        ┆            ┆           ┆                │
│ "Contr…   ┆       ┆                 ┆     ┆   ┆        ┆            ┆           ┆                │
└───────────┴───────┴─────────────────┴─────┴───┴────────┴────────────┴───────────┴────────────────┘

Description of metadata columns:

- **asin** - ID of the product, e.g. 0000031852
- **title** - name of the product
- **feature** - bullet-point format features of the product
- **description** - description of the product
- **price** - price in US dollars (at time of crawl)
- **imageURL** - url of the product image
- **imageURLHighRes** - url of the high resolution product image
- **also buy**, **also view**, **similar_item** - related products
- **rank** - sales rank information
- **brand** - brand name
- **category** - list of categories the product belongs to
- **main_cat** - main category of the product
- **date** - date when product was published
- **fit**, **tech1**, **tech2** - unrelated to Video Games category

Now we count num of users and items, we need at least 1000 of both

In [7]:
print(f'Num of users: {dataset['reviewerID'].n_unique()}')
print(f'Num of items: {dataset['asin'].n_unique()}')
assert dataset['reviewerID'].n_unique() >= 10000
assert dataset['asin'].n_unique() >= 10000

Num of users: 55223
Num of items: 17408